name: CI Pipeline

on:
  push:
    branches:
      - main
jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Install dependencies
      - name: Install dependencies
        run: make install

      # Run unit tests
      - name: Run unit tests
        run: make test

  test-api:
    runs-on: ubuntu-latest
    needs: setup-environment

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Start the app and test API endpoints
      - name: Test API Endpoints
        run: make test-api

  docker-validation:
    runs-on: ubuntu-latest
    needs: setup-environment

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Test the Docker container
      - name: Test Docker Container
        run: |
          make docker-run &
          sleep 10
          make test-api
          docker stop $(docker ps -q --filter "ancestor=health-calculator:latest")
          docker rm $(docker ps -aq --filter "ancestor=health-calculator:latest")